### ISSUE TITLE
Lisensi

### ISSUE THREAD

**Issue by cyberzilla** [kamshory/PlanetbiruFileManager#2]
Apakah plugin ini berbayar?

**Comment by kamshory** [comment]
Untuk yang dishare di GitHub semuanya gratis asalkan digunakan dengan baik. Jangan digunakan untuk membangun aplikasi yang melanggar hukum dan norma yang berlaku.

**Comment by cyberzilla** [comment]
Terima kasih mas.

Syukran, jazaakumullah khairan

**Comment by kamshory** [comment]
sama-sama mas. minta dukungan untuk www.planetbiru.com ya. supaya muslim punya media sosial sendiri.
